# Generated by Django 6.1.1 on 2026-09-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_pre_registration_open_event_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_optional',
            field=models.BooleanField(default=True, help_text='If enabled, registration is optional for attendees.'),
        ),
    ]
