# Generated by Django 6.1.1 on 2026-09-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_registration_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_available_to_all',
            field=models.BooleanField(default=True, help_text='If enabled, the registration form is available to everyone.'),
        ),
    ]
